# Generated by Django 4.1.7 on 2023-08-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=30)),
                ("Last_Name", models.CharField(max_length=40)),
                ("Phone", models.IntegerField(default=0)),
                ("Movie_Name", models.CharField(max_length=50)),
                ("Message", models.TextField(blank=True)),
            ],
        ),
    ]
