# Generated by Django 4.1.7 on 2023-08-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_gallary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gallary",
            old_name="Description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="gallary",
            old_name="Image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="gallary",
            old_name="Title",
            new_name="title",
        ),
    ]
