# Generated by Django 4.1.7 on 2023-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_rename_description_gallary_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="upload/images")),
                ("name", models.CharField(max_length=30)),
                ("story", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=200)),
            ],
        ),
    ]
