# Generated by Django 4.1.7 on 2023-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image", models.ImageField(upload_to="upload/images")),
                ("Title", models.CharField(max_length=30)),
                ("desc", models.CharField(max_length=200)),
            ],
        ),
    ]
